//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalindromosWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        public int Id { get; set; }
        public string Palabra1 { get; set; }
        public bool Palindromo { get; set; }
    }

    public partial class Palabra_2
    {
        public string Palabra1 { get; set; }
    }
}
